/**
 * recategorize-catalog.ts: fix meal-type categories in the bundled catalog.
 *
 * The original build-time classifier (scripts/build-catalog.ts `classify`)
 * looked only at the scraped category + title and defaulted everything it
 * couldn't place to "Dinner". That dumped a lot of desserts, drinks, breads,
 * etc. into Dinner ("3 - Berry Sundaes", "A-Plus Hot Chocolate"...).
 *
 * This pass re-derives the category from title + ingredients + instructions,
 * but CONSERVATIVELY: it only MOVES a recipe when there is a confident signal,
 * otherwise it keeps whatever category the record already has. That targets the
 * obvious mis-tags without churning the whole corpus (and without inventing new
 * weird tags, which is the exact thing we're fixing).
 *
 *   npx -y tsx scripts/recategorize-catalog.ts          # dry run: report only
 *   npx -y tsx scripts/recategorize-catalog.ts --write  # rewrite src/data/catalog.ts
 *
 * Everything except the category index (`c`) is left untouched.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CATALOG } from "../src/data/catalog";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..");
const OUT_CATALOG = resolve(REPO, "src/data/catalog.ts");

interface Rec {
  i: string; t: string; c: number; d: string; m: number; s: number;
  g: string[]; n: string[]; u: string; k: string[]; z?: number[]; a?: string[];
}
interface Catalog {
  v: number; generatedAt: string; rewrittenAt?: string; count: number;
  categories: string[]; r: Rec[];
}

const cat = CATALOG as unknown as Catalog;
const CATS = cat.categories;
const idxOf = (name: string): number => CATS.indexOf(name);
// The classifier now lives in scripts/lib/classifyCategory.ts — a second
// corpus (USDA MyPlate) needs the same rules, and two tuned copies would
// drift into filing the same dish differently depending on the pipeline.
import { confidentCategory } from "./lib/classifyCategory";


// ── Run ────────────────────────────────────────────────────────────────────

const changes: Array<{ from: string; to: string; title: string }> = [];
for (const r of cat.r) {
  const want = confidentCategory(r);
  if (!want) continue;
  const wi = idxOf(want);
  if (wi < 0 || wi === r.c) continue;
  changes.push({ from: CATS[r.c], to: want, title: r.t });
  r.c = wi;
}

// Report.
const before = new Map<string, number>();
const after = new Map<string, number>();
const moveMatrix = new Map<string, number>();
for (const c of changes) {
  const k = `${c.from} -> ${c.to}`;
  moveMatrix.set(k, (moveMatrix.get(k) ?? 0) + 1);
}
for (const r of cat.r) after.set(CATS[r.c], (after.get(CATS[r.c]) ?? 0) + 1);
// before = after with the changes reversed
for (const r of cat.r) before.set(CATS[r.c], (before.get(CATS[r.c]) ?? 0));
for (const c of changes) {
  before.set(c.from, (before.get(c.from) ?? 0) + 1);
  before.set(c.to, (before.get(c.to) ?? 0) - 1);
}

console.log(`reclassified ${changes.length} of ${cat.r.length} recipes\n`);
console.log("moves:");
for (const [k, n] of [...moveMatrix.entries()].sort((a, b) => b[1] - a[1])) {
  console.log(`  ${k.padEnd(24)} ${n}`);
}
console.log("\ncategory counts (after):");
for (const name of CATS) console.log(`  ${name.padEnd(11)} ${after.get(name) ?? 0}`);

console.log("\nsample of changes:");
for (const c of changes.slice(0, 40)) {
  console.log(`  ${c.from.padEnd(10)} -> ${c.to.padEnd(10)} | ${c.title}`);
}

// Emit a tight, idempotent SQL patch for the DB-backed catalog (recipes-db):
// only the rows whose category changed, matched by title among catalog rows.
// Rerunnable (plain UPDATEs), and far lighter than a full re-seed.
{
  const sqlEsc = (s: string) => s.replace(/'/g, "''");
  const lines = [
    "-- Recategorization patch for the public catalog (source='catalog').",
    "-- Idempotent: re-running sets the same categories. Run on dev, then prod.",
    "begin;",
    ...changes.map(
      (c) =>
        `update public.recipes set category='${sqlEsc(c.to)}' ` +
        `where source='catalog' and title='${sqlEsc(c.title)}';`,
    ),
    "commit;",
  ];
  const outFile = resolve(REPO, "scripts", "recategorize-updates.sql");
  writeFileSync(outFile, lines.join("\n") + "\n", "utf8");
  console.log(`\nwrote ${changes.length} UPDATEs to ${outFile}`);
}

if (process.argv.includes("--write")) {
  const payload = {
    v: cat.v,
    generatedAt: cat.generatedAt,
    rewrittenAt: cat.rewrittenAt,
    recategorizedAt: new Date().toISOString(),
    count: cat.r.length,
    categories: cat.categories,
    r: cat.r,
  };
  const json = JSON.stringify(payload);
  const module =
    "// AUTO-GENERATED by scripts/build-catalog.ts, instructions reworded by\n" +
    "// scripts/rewrite-catalog.ts, categories corrected by\n" +
    "// scripts/recategorize-catalog.ts. Do not edit by hand.\n" +
    `export const CATALOG = ${json} as {\n` +
    "  v: number; generatedAt: string; rewrittenAt?: string; recategorizedAt?: string; count: number; categories: string[]; r: unknown[];\n" +
    "};\n";
  writeFileSync(OUT_CATALOG, module, "utf8");
  console.log(`\nwrote ${OUT_CATALOG} (${(module.length / 1024 / 1024).toFixed(2)} MB)`);
} else {
  console.log("\n(dry run — pass --write to rewrite src/data/catalog.ts)");
}
