-- Recategorization patch for the public catalog (source='catalog').
-- Idempotent: re-running sets the same categories. Run on dev, then prod.
begin;
update public.recipes set category='Salad' where source='catalog' and title='24 Hour Salad';
update public.recipes set category='Dessert' where source='catalog' and title='3 - Berry Sundaes';
update public.recipes set category='Drink' where source='catalog' and title='A-Plus Hot Chocolate';
update public.recipes set category='Drink' where source='catalog' and title='Adult Slushies';
update public.recipes set category='Salad' where source='catalog' and title='Affy Tapple Salad';
update public.recipes set category='Breakfast' where source='catalog' and title='Almond Maple Granola';
update public.recipes set category='Side' where source='catalog' and title='Super Stuffing';
update public.recipes set category='Dessert' where source='catalog' and title='American Trifle';
update public.recipes set category='Bread' where source='catalog' and title='Amish Friendship Bread Starter';
update public.recipes set category='Breakfast' where source='catalog' and title='Amish Sourdough Pancakes';
update public.recipes set category='Appetizer' where source='catalog' and title='Andie''s Stuffed Mushrooms';
update public.recipes set category='Dessert' where source='catalog' and title='Anise Almond Biscotti';
update public.recipes set category='Dessert' where source='catalog' and title='Anise Biscotti';
update public.recipes set category='Dessert' where source='catalog' and title='Anise Walnut Biscotti';
update public.recipes set category='Side' where source='catalog' and title='Apple and Pecan Stuffing';
update public.recipes set category='Bread' where source='catalog' and title='Apple and Sausage Cornbread Stuffing';
update public.recipes set category='Breakfast' where source='catalog' and title='Apple Cider Pancakes';
update public.recipes set category='Breakfast' where source='catalog' and title='Apple Cinnamon Oatmeal Bread';
update public.recipes set category='Side' where source='catalog' and title='Apple Nut Stuffing';
update public.recipes set category='Breakfast' where source='catalog' and title='Apple Oatmeal Crisp';
update public.recipes set category='Drink' where source='catalog' and title='Apple Pie Cider';
update public.recipes set category='Breakfast' where source='catalog' and title='Apple Yogurt Pancakes';
update public.recipes set category='Side' where source='catalog' and title='Apple, Sausage, Bacon, and Mushroom Stuffing';
update public.recipes set category='Bread' where source='catalog' and title='Applesauce Bread II';
update public.recipes set category='Breakfast' where source='catalog' and title='Applesauce French Toast';
update public.recipes set category='Bread' where source='catalog' and title='Applesauce Raisin Bread';
update public.recipes set category='Lunch' where source='catalog' and title='Applesauce Sandwich';
update public.recipes set category='Bread' where source='catalog' and title='Applesauce Wheat Blueberry Muffins';
update public.recipes set category='Bread' where source='catalog' and title='Applesauce Zucchini Bread';
update public.recipes set category='Lunch' where source='catalog' and title='Asparagus Wrap';
update public.recipes set category='Side' where source='catalog' and title='Au Gratin Potatoes';
update public.recipes set category='Side' where source='catalog' and title='Au Gratin Potatoes II';
update public.recipes set category='Dessert' where source='catalog' and title='Australian English Trifle';
update public.recipes set category='Breakfast' where source='catalog' and title='Austrian Pancake';
update public.recipes set category='Appetizer' where source='catalog' and title='Authentic Chinese Egg Rolls (from a Chinese person)';
update public.recipes set category='Appetizer' where source='catalog' and title='Avocado and Sun-Dried Tomato Spring Rolls';
update public.recipes set category='Appetizer' where source='catalog' and title='Bacon and Cheddar Stuffed Mushrooms';
update public.recipes set category='Appetizer' where source='catalog' and title='Bacon Cheddar Jalapeno Poppers';
update public.recipes set category='Lunch' where source='catalog' and title='Bacon Olive Wraps';
update public.recipes set category='Breakfast' where source='catalog' and title='Bacon Quiche Tarts';
update public.recipes set category='Appetizer' where source='catalog' and title='Bacon Wrapped Stuffed Mushrooms';
update public.recipes set category='Breakfast' where source='catalog' and title='Baked Apple-Pecan Maple Pancakes';
update public.recipes set category='Side' where source='catalog' and title='Baked Beans I';
update public.recipes set category='Side' where source='catalog' and title='Baked Beans II';
update public.recipes set category='Side' where source='catalog' and title='Baked Beans III';
update public.recipes set category='Side' where source='catalog' and title='Baked Beans, Texas Ranger';
update public.recipes set category='Dessert' where source='catalog' and title='Baked Flan';
update public.recipes set category='Breakfast' where source='catalog' and title='Baked Omelet Pie';
update public.recipes set category='Breakfast' where source='catalog' and title='Baked Omelet Roll';
update public.recipes set category='Breakfast' where source='catalog' and title='Baked Pancake Squares';
update public.recipes set category='Breakfast' where source='catalog' and title='Baked Pancakes with Sausages';
update public.recipes set category='Appetizer' where source='catalog' and title='Baked Pork Spring Rolls';
update public.recipes set category='Bread' where source='catalog' and title='Baked Pretzels';
update public.recipes set category='Side' where source='catalog' and title='Baked Seafood Au Gratin';
update public.recipes set category='Lunch' where source='catalog' and title='Baked Tofu Spinach Wrap';
update public.recipes set category='Dessert' where source='catalog' and title='Baklava';
update public.recipes set category='Bread' where source='catalog' and title='Banana Bread Crumb Pudding';
update public.recipes set category='Breakfast' where source='catalog' and title='Banana Bread French Toast';
update public.recipes set category='Breakfast' where source='catalog' and title='Banana Frittata';
update public.recipes set category='Breakfast' where source='catalog' and title='Banana Nut Oatmeal Bread';
update public.recipes set category='Breakfast' where source='catalog' and title='Banana Oatmeal Bread';
update public.recipes set category='Breakfast' where source='catalog' and title='Banana Pancake Muffins';
update public.recipes set category='Breakfast' where source='catalog' and title='Banana Pancakes';
update public.recipes set category='Breakfast' where source='catalog' and title='Banana Pancakes II';
update public.recipes set category='Appetizer' where source='catalog' and title='Banana Spring Rolls';
update public.recipes set category='Side' where source='catalog' and title='Bar-B-Q Baked Beans';
update public.recipes set category='Side' where source='catalog' and title='Basic Yummy Stuffing';
update public.recipes set category='Bread' where source='catalog' and title='Basil Pesto Bread';
update public.recipes set category='Bread' where source='catalog' and title='Basil Pesto Bread Rounds';
update public.recipes set category='Appetizer' where source='catalog' and title='Best Egg Rolls';
update public.recipes set category='Lunch' where source='catalog' and title='Big Brunch Quesadillas';
update public.recipes set category='Lunch' where source='catalog' and title='Cheesy Little Link Snack Wraps';
update public.recipes set category='Breakfast' where source='catalog' and title='Easy Granola Bars';
update public.recipes set category='Breakfast' where source='catalog' and title='European Muesli';
update public.recipes set category='Sauce' where source='catalog' and title='Flavored Milk Syrup';
update public.recipes set category='Breakfast' where source='catalog' and title='Granola Bars III';
update public.recipes set category='Breakfast' where source='catalog' and title='Groovy Grannies'' Waffle-y Snack Mix';
update public.recipes set category='Breakfast' where source='catalog' and title='Honey Nut Granola';
update public.recipes set category='Breakfast' where source='catalog' and title='Nutty Granola II';
commit;
